version: 1.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- cmd: .\build.cmd
test:
  assemblies: 'Source\**\*.Specs.dll'
after_test:
- cmd: >-
    cd .\Build
    RunJavascriptSpecs.cmd
deploy: off
