version: 1.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
  - cmd: .\build.cmd BuildAndPackage
test:
  assemblies: 'Source\**\*.Specs.dll'
after_test:
  - cmd: >-
    echo "Current directory is:"
    cd 
deploy: off
on_success:
  - cmd: >-
    echo "Hello world"
artifacts:
  - path: artifacts\**\*
